name: redux_stream
description: |
  Redux Architecture for Flutter 3.0+
  'redux_stream' library is Experimental.
version: 0.3.0
homepage: https://github.com/vivitainc/flutter_redux_stream

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  provider: ^6.0.0
  logger: ^1.0.0
  async_notify: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
