name: redux_stream2
description: |
  Redux Architecture for Flutter 3.0+
  'redux_stream' library is Experimental.
  fork from https://github.com/vivitainc/flutter_redux_stream
version: 1.0.0+1
homepage: https://github.com/eaglesakura/flutter_redux_stream

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  logger: ^1.0.0
  async_notify: ^0.0.2
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
