name: "Flutter: Package testing"
on:
  push:
jobs:
  flutter-library-test:
    name: "Flutter: Package testing"
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.event.head_commit.message, 'wip:') == false
    env:
      _JAVA_OPTIONS: "-Xmx4g -Dfile.encoding=UTF-8"
      TZ: Asia/Tokyo
      JAVA_VERSION: "11"
    steps:
      - uses: actions/checkout@v3
      - name: "environments / java11"
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
      - name: "install / fvm"
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
          sudo apt-get install dart
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: "install / fvm / flutter"
        run: |
          fvm install
      - name: "cache / dart"
        uses: actions/cache@v3
        with:
          path: $HOME/.pub-cache
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/cache-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-dart-
      - name: "environments"
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "PWD=$PWD"
          echo "java `java -version`: `which java`"
          echo "gradle=`which gradle`"
          echo "flutter=`fvm flutter --version`"
          echo "dart=`which dart`"
          ls -al
          chmod +x ./gradlew
      - name: "flutter / pub upgrade"
        run: ./gradlew flutterPubUpgrade
      - name: "flutter / format"
        run: ./gradlew flutterValidateFormat
      - name: "flutter / analyze"
        run: ./gradlew flutterAnalyze
      - name: "flutter / test"
        run: ./gradlew flutterTest
